/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EWasteGuideRouteImport } from './routes/e-waste-guide'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalysesRouteImport } from './routes/admin.analyses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminEWasteRouteImport } from './routes/admin.e-waste'
import { Route as AdminModelPerformanceRouteImport } from './routes/admin.model-performance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EWasteGuideRoute = EWasteGuideRouteImport.update({
  id: '/e-waste-guide',
  path: '/e-waste-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalysesRoute = AdminAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEWasteRoute = AdminEWasteRouteImport.update({
  id: '/e-waste',
  path: '/e-waste',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelPerformanceRoute = AdminModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/e-waste-guide': typeof EWasteGuideRoute
  '/results': typeof ResultsRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/e-waste': typeof AdminEWasteRoute
  '/admin/model-performance': typeof AdminModelPerformanceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/e-waste-guide': typeof EWasteGuideRoute
  '/results': typeof ResultsRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/e-waste': typeof AdminEWasteRoute
  '/admin/model-performance': typeof AdminModelPerformanceRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/e-waste-guide': typeof EWasteGuideRoute
  '/results': typeof ResultsRoute
  '/admin/analyses': typeof AdminAnalysesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/e-waste': typeof AdminEWasteRoute
  '/admin/model-performance': typeof AdminModelPerformanceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/dashboard'
    | '/e-waste-guide'
    | '/results'
    | '/admin/analyses'
    | '/admin/analytics'
    | '/admin/e-waste'
    | '/admin/model-performance'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/dashboard'
    | '/e-waste-guide'
    | '/results'
    | '/admin/analyses'
    | '/admin/analytics'
    | '/admin/e-waste'
    | '/admin/model-performance'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/dashboard'
    | '/e-waste-guide'
    | '/results'
    | '/admin/analyses'
    | '/admin/analytics'
    | '/admin/e-waste'
    | '/admin/model-performance'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyzeRoute: typeof AnalyzeRoute
  DashboardRoute: typeof DashboardRoute
  EWasteGuideRoute: typeof EWasteGuideRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-waste-guide': {
      id: '/e-waste-guide'
      path: '/e-waste-guide'
      fullPath: '/e-waste-guide'
      preLoaderRoute: typeof EWasteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analyses': {
      id: '/admin/analyses'
      path: '/analyses'
      fullPath: '/admin/analyses'
      preLoaderRoute: typeof AdminAnalysesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/e-waste': {
      id: '/admin/e-waste'
      path: '/e-waste'
      fullPath: '/admin/e-waste'
      preLoaderRoute: typeof AdminEWasteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-performance': {
      id: '/admin/model-performance'
      path: '/model-performance'
      fullPath: '/admin/model-performance'
      preLoaderRoute: typeof AdminModelPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalysesRoute: typeof AdminAnalysesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEWasteRoute: typeof AdminEWasteRoute
  AdminModelPerformanceRoute: typeof AdminModelPerformanceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalysesRoute: AdminAnalysesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEWasteRoute: AdminEWasteRoute,
  AdminModelPerformanceRoute: AdminModelPerformanceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyzeRoute: AnalyzeRoute,
  DashboardRoute: DashboardRoute,
  EWasteGuideRoute: EWasteGuideRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
